services:
  - type: worker
    name: parking-simulator
    env: node
    buildCommand: npm install
    startCommand: node dist/parkingSimulator.js
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18.x 